# Generated by Django 4.0.4 on 2022-05-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_completed_completed_todoitem_completed_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
