# Generated by Django 4.0.4 on 2022-05-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_delete_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed_item',
        ),
    ]
